name: production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout SCM
      uses: actions/checkout@v4 #git pull
    
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_IMAGE }} .

    - name: Login To Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Push Image To Registry
      run: docker push ${{ secrets.DOCKER_IMAGE }}

  deploy:

    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Execute SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
           docker pull ${{ secrets.DOCKER_IMAGE }}
           docker compose down 
           docker compose up -d
